/* Conductor terminal cloud sync + reverse-route helper. */
(() => {
  const URL='https://ubhfigqpsepnpokrbdyo.supabase.co/rest/v1/ticket_shared_state';
  const KEY='sb_publishable_yN8W8pvQq8hWsYMO8z1Rzw_6zKQ-8D1';
  const ROW='main';
  const LOCAL_KEYS=['conductor_routes','conductor_tickets','conductor_shift_active','conductor_name','conductor_terminal_id','conductor_org_name','conductor_ticket_footer','conductor_paper_width','conductor_last_num','conductor_operations','conductor_compositions','conductor_current_composition','conductor_shift_started_at'];
  const headers={'apikey':KEY,'Authorization':'Bearer '+KEY,'Content-Type':'application/json'};
  let timer=null,saving=false,queued=false,hydrating=false,watcherInstalled=false,originalSetItem=null,originalRemoveItem=null;
  function getLocal(k,d){const v=localStorage.getItem(k);if(v===null)return d;try{return JSON.parse(v)}catch(_){return v}}
  function localState(){return{routes:getLocal('conductor_routes',[]),tickets:getLocal('conductor_tickets',[]),shiftActive:getLocal('conductor_shift_active',false)===true||getLocal('conductor_shift_active',false)==='true',conductorName:getLocal('conductor_name','Кондуктор №1'),terminalID:getLocal('conductor_terminal_id','POS-88'),orgName:getLocal('conductor_org_name','Узкоколейная ЖД'),ticketFooter:getLocal('conductor_ticket_footer','Счастливого пути!'),paperWidth:getLocal('conductor_paper_width','58mm'),lastTicketNum:Number(getLocal('conductor_last_num',1001)),operations:getLocal('conductor_operations',[]),compositions:getLocal('conductor_compositions',[]),currentComposition:getLocal('conductor_current_composition',''),shiftStartedAt:getLocal('conductor_shift_started_at','')}}
  function status(t,ok=true){const e=document.getElementById('cloudStatus');if(e)e.innerHTML='<span class="sync-dot '+(ok?'sync-ok':'sync-wait')+'"></span>'+t}
  function key(x,type){if(!x||typeof x!=='object')return null;if(type==='tickets')return String(x.num??x.number??x.id??'');if(type==='routes')return String(x.id??x.name??'');return String(x.id??x.num??x.number??'')}
  function time(x){const t=x&&(x.updatedAt||x.updated_at||x.cancelledAt||x.createdAt||x.created_at);const n=t?Date.parse(t):NaN;return Number.isFinite(n)?n:0}
  function mergeArray(a,b,type){const m=new Map();(b||[]).forEach(x=>{const k=key(x,type);if(k)m.set(k,x)});(a||[]).forEach(x=>{const k=key(x,type);if(!k){m.set('__'+Math.random(),x);return}const old=m.get(k);if(!old||time(x)>=time(old)||(type==='tickets'&&x.status==='cancelled'&&old.status!=='cancelled'))m.set(k,x)});return Array.from(m.values())}
  function merge(a,b){a=a||{};b=b||{};const m={...b,...a};m.routes=mergeArray(a.routes,b.routes,'routes');m.tickets=mergeArray(a.tickets,b.tickets,'tickets');m.operations=mergeArray(a.operations,b.operations,'operations');m.compositions=mergeArray(a.compositions,b.compositions,'compositions');m.lastTicketNum=Math.max(Number(a.lastTicketNum)||0,Number(b.lastTicketNum)||0,1001);return m}
  function write(data){hydrating=true;try{if(typeof state!=='undefined')state={...state,...data};const w=(k,v)=>originalSetItem(k,typeof v==='string'?v:JSON.stringify(v));w('conductor_routes',data.routes||[]);w('conductor_tickets',data.tickets||[]);w('conductor_shift_active',data.shiftActive?'true':'false');w('conductor_name',data.conductorName||'');w('conductor_terminal_id',data.terminalID||'');w('conductor_org_name',data.orgName||'');w('conductor_ticket_footer',data.ticketFooter||'');w('conductor_paper_width',data.paperWidth||'58mm');w('conductor_last_num',String(data.lastTicketNum||1001));w('conductor_operations',data.operations||[]);w('conductor_compositions',data.compositions||[]);w('conductor_current_composition',data.currentComposition||'');w('conductor_shift_started_at',data.shiftStartedAt||'');if(typeof renderRoutesTable==='function')renderRoutesTable();if(typeof updateShiftStats==='function')updateShiftStats();if(typeof renderOperations==='function')renderOperations();if(typeof searchTickets==='function')searchTickets();if(typeof updatePreview==='function')updatePreview();const ids={conductorName:'conductorName',terminalID:'terminalID',orgName:'orgName',ticketFooter:'ticketFooter',paperWidth:'paperWidthSelect'};Object.entries(ids).forEach(([k,id])=>{const e=document.getElementById(id);if(e&&data[k]!==undefined)e.value=data[k]});}finally{hydrating=false}}
  async function cloud(){const r=await fetch(URL+'?select=data,updated_at&id=eq.main',{headers:{'apikey':KEY,'Authorization':'Bearer '+KEY},cache:'no-store'});if(!r.ok)throw Error('GET '+r.status);const x=await r.json();return x&&x[0]?x[0]:null}
  async function save(){if(saving){queued=true;return}saving=true;try{const l=localState(),r=await cloud(),m=r&&r.data&&Object.keys(r.data).length?merge(l,r.data):l;write(m);const q=await fetch(URL,{method:'POST',headers:{...headers,'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:ROW,data:m,updated_at:new Date().toISOString()})});if(!q.ok)throw Error('POST '+q.status);status('☁️ Синхронизировано')}catch(e){console.error(e);status('⚠️ Ошибка синхронизации',false)}finally{saving=false;if(queued){queued=false;save()}}}
  function watch(){if(watcherInstalled)return;watcherInstalled=true;originalSetItem=localStorage.setItem.bind(localStorage);originalRemoveItem=localStorage.removeItem.bind(localStorage);localStorage.setItem=function(k,v){const r=originalSetItem(k,v);if(LOCAL_KEYS.includes(k))schedule();return r};localStorage.removeItem=function(k){const r=originalRemoveItem(k);if(LOCAL_KEYS.includes(k))schedule();return r}}
  function schedule(){if(hydrating)return;clearTimeout(timer);timer=setTimeout(save,700)}
  async function pull(base){try{status('☁️ Синхронизация…');const r=await cloud(),l=base||localState();if(r&&r.data&&Object.keys(r.data).length){const m=merge(l,r.data);write(m);if(JSON.stringify(m)!==JSON.stringify(r.data)){const q=await fetch(URL,{method:'POST',headers:{...headers,'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:ROW,data:m,updated_at:new Date().toISOString()})});if(!q.ok)throw Error('POST '+q.status)}}else if(l.routes.length||l.tickets.length||l.operations.length)await save();status('☁️ Синхронизировано')}catch(e){console.error(e);status('⚠️ Ошибка синхронизации',false)}}
  function reverseName(n){const s=String(n||'').trim();for(const p of ['→','↔',' - ',' — ','–','-'])if(s.includes(p)){const a=s.split(p).map(x=>x.trim()).filter(Boolean);if(a.length===2)return a[1]+'-'+a[0]}return s?' '+s+' (обратный)':'Обратный маршрут'}
  function reverseButton(){const saveBtn=document.getElementById('routeSaveButton');if(!saveBtn||document.getElementById('routePairButton'))return;const b=document.createElement('button');b.id='routePairButton';b.className='btn btn-outline';b.type='button';b.textContent='↔️ Сохранить + обратный маршрут';b.onclick=window.saveRoutePair;saveBtn.parentElement.appendChild(b)}
  window.saveRoutePair=function(){const name=document.getElementById('newRouteName')?.value.trim(),transport=document.getElementById('newRouteTransport')?.value,fare=parseFloat(document.getElementById('newRouteFarePerStop')?.value||0),min=parseFloat(document.getElementById('newRouteMinPrice')?.value||0),raw=document.getElementById('newRouteStops')?.value.trim();if(!name||!raw)return alert('Заполните название маршрута и список остановок!');const stops=raw.split(',').map(x=>x.trim()).filter(Boolean);if(stops.length<2)return alert('Для обратного маршрута нужно минимум 2 остановки.');const rn=reverseName(name),rev=stops.slice().reverse();if(editingRouteId){const r=state.routes.find(x=>x.id===editingRouteId);if(r){r.name=name;r.transport=transport;r.farePerStop=fare;r.minPrice=min;r.stops=stops;if(!state.routes.some(x=>x.name===rn&&JSON.stringify(x.stops||[])===JSON.stringify(rev)))state.routes.push({id:'route_'+Date.now()+'_rev',name:rn,transport,farePerStop:fare,minPrice:min,stops:rev})}}else{const id='route_'+Date.now();state.routes.push({id,name,transport,farePerStop:fare,minPrice:min,stops});if(!state.routes.some(x=>x.name===rn&&JSON.stringify(x.stops||[])===JSON.stringify(rev)))state.routes.push({id:id+'_rev',name:rn,transport,farePerStop:fare,minPrice:min,stops:rev})}localStorage.setItem('conductor_routes',JSON.stringify(state.routes));if(typeof renderRoutesTable==='function')renderRoutesTable();if(typeof updateRouteDropdowns==='function')updateRouteDropdowns();if(typeof resetRouteForm==='function')resetRouteForm();save();soundBeep(1200,80);alert('Созданы два маршрута: «'+name+'» и «'+rn+'».')};
  function start(){if(window.__conductorCloudSyncStarted)return;window.__conductorCloudSyncStarted=true;watch();window.forceReliableCloudSync=save;window.syncConductorData=save;window.ticketCloudSave=save;reverseButton();const snapshot=localState();setTimeout(()=>pull(snapshot),900);setTimeout(()=>{window.forceReliableCloudSync=save;window.syncConductorData=save;window.ticketCloudSave=save},1100);window.addEventListener('focus',()=>pull());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')pull()});window.addEventListener('beforeunload',()=>{if(!hydrating)save()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();